import { Weapon } from './Weapon';

export const revolverWeapon: Weapon = {
  config: {
    id: 'revolver',
    label: 'Revolver lourd',
    damage: 28,
    cooldownMs: 250,
    recoilForce: 205,
    projectileBehavior: 'straight',
    wallInteraction: 'destroy',
    projectile: {
      speed: 600,
      damage: 28,
      maxRangePx: 520,
      maxPlayerHits: 1,
      gravityScale: 0,
    },
    bloodProjection: {
      spreadDegrees: 18,
      particleCount: 8,
      speedMin: 50,
      speedMax: 130,
      sprayOffset: 6,
      lifetimeMin: 180,
      lifetimeMax: 420,
    },
    audio: {
      shoot: [{ startFrequency: 420, endFrequency: 220, durationMs: 80, gain: 0.05 }],
      impact: [{ startFrequency: 210, endFrequency: 95, durationMs: 90, gain: 0.048 }],
      projection: [{ startFrequency: 760, endFrequency: 520, durationMs: 35, gain: 0.018 }],
    },
  },
  iconTexture: 'weapon-icon-revolver',
  muzzleFlashAnimation: 'anim-muzzle-flash-revolver',
  muzzleFlashMs: 100,
  muzzleFlashLengthPx: 28,
  muzzleFlashHeightPx: 6,
  projectileTexture: 'projectile-revolver',
  muzzleFlashTexture: 'muzzle-flash-revolver',
};

export const shotgunWeapon: Weapon = {
  config: {
    id: 'shotgun',
    label: 'Fusil à pompe',
    damage: 16,
    cooldownMs: 560,
    recoilForce: 295,
    projectileBehavior: 'straight',
    wallInteraction: 'destroy',
    projectile: {
      speed: 540,
      damage: 16,
      pelletCount: 5,
      spreadDegrees: 30,
      maxRangePx: 265,
      maxPlayerHits: 1,
      gravityScale: 0,
    },
    bloodProjection: {
      spreadDegrees: 36,
      particleCount: 14,
      speedMin: 40,
      speedMax: 170,
      sprayOffset: 9,
      lifetimeMin: 260,
      lifetimeMax: 520,
    },
    audio: {
      shoot: [
        { startFrequency: 185, endFrequency: 90, durationMs: 80, gain: 0.055 },
        { startFrequency: 195, endFrequency: 75, durationMs: 80, gain: 0.05, delayMs: 30 },
        { startFrequency: 205, endFrequency: 85, durationMs: 80, gain: 0.05, delayMs: 60 },
      ],
      impact: [{ startFrequency: 165, endFrequency: 62, durationMs: 90, gain: 0.048 }],
      projection: [{ startFrequency: 700, endFrequency: 460, durationMs: 36, gain: 0.017 }],
    },
  },
  iconTexture: 'weapon-icon-shotgun',
  muzzleFlashAnimation: 'anim-muzzle-flash-shotgun',
  muzzleFlashMs: 90,
  muzzleFlashLengthPx: 36,
  muzzleFlashHeightPx: 8,
  projectileTexture: 'projectile-shotgun',
  muzzleFlashTexture: 'muzzle-flash-shotgun',
};

export const smgWeapon: Weapon = {
  config: {
    id: 'smg',
    label: 'Pistolet-mitrailleur',
    damage: 8,
    cooldownMs: 90,
    recoilForce: 175,
    fireMode: 'automatic',
    projectileBehavior: 'straight',
    wallInteraction: 'destroy',
    projectile: {
      speed: 560,
      damage: 8,
      spreadDegrees: 5,
      spreadIncreaseDegrees: 1.8,
      spreadMaxDegrees: 17,
      spreadResetMs: 220,
      trailIntervalMs: 45,
      trailParticleScale: 0.62,
      maxRangePx: 410,
      maxPlayerHits: 1,
      gravityScale: 0,
    },
    bloodProjection: {
      spreadDegrees: 22,
      particleCount: 7,
      speedMin: 42,
      speedMax: 115,
      sprayOffset: 6,
      lifetimeMin: 120,
      lifetimeMax: 260,
    },
    audio: {
      shoot: [{ startFrequency: 360, endFrequency: 160, durationMs: 55, gain: 0.043 }],
      impact: [{ startFrequency: 155, endFrequency: 60, durationMs: 80, gain: 0.044 }],
      projection: [{ startFrequency: 740, endFrequency: 490, durationMs: 34, gain: 0.014 }],
    },
  },
  iconTexture: 'weapon-icon-smg',
  muzzleFlashAnimation: 'anim-muzzle-flash-smg',
  muzzleFlashMs: 64,
  muzzleFlashLengthPx: 30,
  muzzleFlashHeightPx: 6,
  projectileTexture: 'projectile-shotgun',
  muzzleFlashTexture: 'muzzle-flash-smg',
};

export const crossbowWeapon: Weapon = {
  config: {
    id: 'crossbow',
    label: 'Arbalète',
    damage: 40,
    cooldownMs: 720,
    recoilForce: 265,
    projectileBehavior: 'arc',
    wallInteraction: 'passThrough',
    wallStickingMs: 280,
    projectile: {
      speed: 360,
      damage: 40,
      spreadDegrees: 2.5,
      maxRangePx: 620,
      maxPlayerHits: 1,
      gravityScale: 0.26,
    },
    bloodProjection: {
      spreadDegrees: 11,
      particleCount: 7,
      speedMin: 52,
      speedMax: 90,
      sprayOffset: 4,
      lifetimeMin: 140,
      lifetimeMax: 300,
    },
    audio: {
      shoot: [{ startFrequency: 270, endFrequency: 110, durationMs: 80, gain: 0.06 }],
      impact: [{ startFrequency: 145, endFrequency: 52, durationMs: 90, gain: 0.05 }],
      projection: [{ startFrequency: 610, endFrequency: 430, durationMs: 34, gain: 0.012 }],
    },
  },
  iconTexture: 'weapon-icon-crossbow',
  muzzleFlashAnimation: 'anim-muzzle-flash-crossbow',
  muzzleFlashMs: 115,
  muzzleFlashLengthPx: 34,
  muzzleFlashHeightPx: 6,
  projectileTexture: 'projectile-crossbow',
  muzzleFlashTexture: 'muzzle-flash-crossbow',
};

export const grenadeWeapon: Weapon = {
  config: {
    id: 'grenade',
    label: 'Lance-grenades',
    damage: 18,
    cooldownMs: 860,
    recoilForce: 255,
    projectileBehavior: 'arc',
    wallInteraction: 'destroy',
    projectile: {
      speed: 320,
      damage: 18,
      maxRangePx: 620,
      maxPlayerHits: 1,
      gravityScale: 0.22,
      explosionRadiusPx: 130,
      explosionDamage: 36,
      explosionKnockback: 280,
      explosionDelayMs: 540,
      explosionPoolCount: 4,
    },
    bloodProjection: {
      spreadDegrees: 24,
      particleCount: 10,
      speedMin: 60,
      speedMax: 140,
      sprayOffset: 8,
      lifetimeMin: 180,
      lifetimeMax: 340,
    },
    audio: {
      shoot: [{ startFrequency: 210, endFrequency: 86, durationMs: 70, gain: 0.05 }],
      impact: [{ startFrequency: 155, endFrequency: 52, durationMs: 90, gain: 0.06 }],
      projection: [{ startFrequency: 720, endFrequency: 410, durationMs: 36, gain: 0.018 }],
    },
  },
  iconTexture: 'weapon-icon-grenade',
  muzzleFlashAnimation: 'anim-muzzle-flash-shotgun',
  muzzleFlashMs: 95,
  muzzleFlashLengthPx: 34,
  muzzleFlashHeightPx: 8,
  projectileTexture: 'projectile-grenade',
  muzzleFlashTexture: 'muzzle-flash-shotgun',
};

export const perforantWeapon: Weapon = {
  config: {
    id: 'perforant',
    label: 'Fusil perforant',
    damage: 38,
    cooldownMs: 430,
    recoilForce: 320,
    projectileBehavior: 'straight',
    wallInteraction: 'passThrough',
    projectile: {
      speed: 620,
      damage: 38,
      spreadDegrees: 4,
      maxRangePx: 700,
      maxPlayerHits: 3,
      gravityScale: 0,
      trailIntervalMs: 26,
      trailParticleScale: 0.58,
    },
    bloodProjection: {
      spreadDegrees: 16,
      particleCount: 9,
      speedMin: 44,
      speedMax: 96,
      sprayOffset: 4,
      lifetimeMin: 130,
      lifetimeMax: 220,
    },
    audio: {
      shoot: [{ startFrequency: 230, endFrequency: 85, durationMs: 95, gain: 0.058 }],
      impact: [{ startFrequency: 122, endFrequency: 52, durationMs: 90, gain: 0.055 }],
      projection: [{ startFrequency: 760, endFrequency: 520, durationMs: 36, gain: 0.013 }],
    },
  },
  iconTexture: 'weapon-icon-perforant',
  muzzleFlashAnimation: 'anim-muzzle-flash-perforant',
  muzzleFlashMs: 135,
  muzzleFlashLengthPx: 38,
  muzzleFlashHeightPx: 8,
  projectileTexture: 'projectile-perforant',
  muzzleFlashTexture: 'muzzle-flash-perforant',
};

export const sawWeapon: Weapon = {
  config: {
    id: 'canon-scie',
    label: 'Canon scié',
    damage: 18,
    cooldownMs: 290,
    recoilForce: 360,
    projectileBehavior: 'straight',
    wallInteraction: 'destroy',
    projectile: {
      speed: 580,
      damage: 18,
      spreadDegrees: 46,
      pelletCount: 2,
      maxRangePx: 250,
      maxPlayerHits: 1,
      gravityScale: 0,
    },
    bloodProjection: {
      spreadDegrees: 52,
      particleCount: 18,
      speedMin: 46,
      speedMax: 118,
      sprayOffset: 10,
      lifetimeMin: 180,
      lifetimeMax: 300,
    },
    audio: {
      shoot: [{ startFrequency: 190, endFrequency: 70, durationMs: 72, gain: 0.052 }],
      impact: [{ startFrequency: 130, endFrequency: 45, durationMs: 82, gain: 0.052 }],
      projection: [{ startFrequency: 690, endFrequency: 440, durationMs: 38, gain: 0.014 }],
    },
  },
  iconTexture: 'weapon-icon-scie',
  muzzleFlashAnimation: 'anim-muzzle-flash-scie',
  muzzleFlashMs: 98,
  muzzleFlashLengthPx: 52,
  muzzleFlashHeightPx: 9,
  projectileTexture: 'projectile-scie',
  muzzleFlashTexture: 'muzzle-flash-scie',
};

export const machetteWeapon: Weapon = {
  config: {
    id: 'machette',
    label: 'Machette',
    damage: 22,
    cooldownMs: 420,
    recoilForce: 245,
    combatMode: 'melee',
    projectileBehavior: 'straight',
    wallInteraction: 'destroy',
    projectile: {
      speed: 1,
      damage: 1,
      maxRangePx: 1,
      maxPlayerHits: 1,
      gravityScale: 0,
    },
    melee: {
      damage: 24,
      cooldownMs: 360,
      rangeWidth: 64,
      rangeHeight: 32,
      rangeOffset: 20,
      knockback: 210,
      windupMs: 78,
      durationMs: 150,
      comboResetMs: 430,
      comboMax: 3,
      comboDamageMultiplier: [1, 1.18, 1.38],
      dashSpeed: 185,
      dashDurationMs: 95,
      parryWindowMs: 170,
      parryCooldownMs: 250,
      bloodParticleScale: 2,
    },
    bloodProjection: {
      spreadDegrees: 34,
      particleCount: 16,
      speedMin: 78,
      speedMax: 150,
      sprayOffset: 13,
      lifetimeMin: 190,
      lifetimeMax: 380,
    },
    audio: {
      shoot: [{ startFrequency: 220, endFrequency: 90, durationMs: 60, gain: 0.05 }],
      impact: [{ startFrequency: 135, endFrequency: 45, durationMs: 85, gain: 0.05 }],
      projection: [{ startFrequency: 700, endFrequency: 470, durationMs: 34, gain: 0.012 }],
    },
  },
  iconTexture: 'weapon-icon-machette',
  muzzleFlashAnimation: 'anim-muzzle-flash-shotgun',
  muzzleFlashMs: 80,
  muzzleFlashLengthPx: 26,
  muzzleFlashHeightPx: 7,
  projectileTexture: 'projectile-shotgun',
  muzzleFlashTexture: 'muzzle-flash-shotgun',
};

export const weaponRegistry: Weapon[] = [
  revolverWeapon,
  shotgunWeapon,
  smgWeapon,
  crossbowWeapon,
  grenadeWeapon,
  perforantWeapon,
  sawWeapon,
  machetteWeapon,
];
