export const CHARACTER_BODY_WIDTH = 32;
export const CHARACTER_BODY_HEIGHT = 48;
export const CHARACTER_FRAME_WIDTH = 48;
export const CHARACTER_FRAME_HEIGHT = 56;
export const CHARACTER_BODY_LEFT = 8;
export const CHARACTER_BODY_TOP = 4;
export const CHARACTER_ORIGIN_X = CHARACTER_FRAME_WIDTH / 2;
export const CHARACTER_ORIGIN_Y = CHARACTER_BODY_TOP + CHARACTER_BODY_HEIGHT;
